name: todo_list_app

services:
  front: &front
    container_name: front
    build:
      context: . # https://qiita.com/sam8helloworld/items/e7fffa9afc82aea68a7a
      dockerfile: ./docker/front/Dockerfile
    volumes:
      - ./front:/var/www/html
    working_dir: /var/www/html
    ports:
      - "3000:3000"
      - "24678:24678" # ホットリロード用
    command: [npm, run, dev]

  storybook:
    <<: *front
    container_name: storybook
    ports:
      - "6006:6006"
    command: npm run storybook

  api:
    container_name: api
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    volumes:
      - ./api:/var/www/html
    expose:
      - 8000

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./api:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api

  db:
    container_name: database
    build:
      context: .
      dockerfile: docker/database/Dockerfile
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: app_db
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - todo_list_app:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOSTS=db
      - PMA_USER=root
      - PMA_PASSWORD=password
    depends_on:
      - db

  mail:
    container_name: mailhog
    image: mailhog/mailhog
    ports:
      - 8025:8025
      - 1025:1025

volumes:
  todo_list_app:
